
    await expect(page.getByText('Checkout')).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Address Details' })).toBeVisible();
    await expect(page.locator('#address_delivery')).toContainText('Your delivery address');
    await expect(page.locator('#address_delivery')).toContainText('Mr. Purnaa chandra');
    await expect(page.locator('#address_delivery')).toContainText('EDS');
    await expect(page.locator('#address_delivery')).toContainText('11 Tels');
    await expect(page.locator('#address_delivery')).toContainText('mtm ap 123456');
    await expect(page.locator('#address_delivery')).toContainText('India');
    await expect(page.locator('#address_delivery')).toContainText('112233445566');
    await expect(page.locator('#address_invoice')).toContainText('Your billing address');
    await expect(page.locator('#address_invoice')).toContainText('Mr. Purnaa chandra');
    await expect(page.locator('#address_invoice')).toContainText('EDS');
    await expect(page.locator('#address_invoice')).toContainText('11 Tels');
    await expect(page.locator('#address_invoice')).toContainText('123');
    await expect(page.locator('#address_invoice')).toContainText('mtm ap 123456');
    await expect(page.locator('#address_invoice')).toContainText('India');
    await expect(page.locator('#address_invoice')).toContainText('112233445566');
    await expect(page.locator('#cart_items')).toContainText('Review Your Order');
    await page.locator('#product-1').getByRole('link', { name: 'Product Image' }).click();
    await expect(page.locator('#product-1')).toContainText('Blue Top');
    await expect(page.getByRole('link', { name: 'Blue Top' })).toBeVisible();
    await expect(page.getByText('Rs. 500')).toBeVisible();
    await expect(page.locator('#product-1')).toContainText('Rs. 500');
    await expect(page.getByRole('row', { name: 'Product Image Blue Top Women' }).getByRole('button')).toBeVisible();
    await expect(page.locator('#product-1')).toContainText('2');
    await expect(page.getByRole('cell', { name: 'Rs. 1000' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'Item' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'Description' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'Price' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'Quantity' })).toBeVisible();
    await expect(page.getByRole('cell', { name: 'Total', exact: true })).toBeVisible();
    await expect(page.getByText('Total Amount')).toBeVisible();
    await expect(page.getByText('Rs. 1800')).toBeVisible();
    await expect(page.getByText('If you would like to add a')).toBeVisible();
    await expect(page.locator('label')).toContainText('If you would like to add a comment about your order, please write it in the field below.');
    await expect(page.locator('textarea[name="message"]')).toBeVisible();
    await expect(page.getByRole('link', { name: 'Place Order' })).toBeVisible();
    await page.getByRole('link', { name: 'Place Order' }).click();